### ISSUE TITLE
Shape Position

### ISSUE THREAD

**Issue by Wavey81** [florian03-1/BlazorSvgEditor#3]
Hello!
I am wondering if it's possible somehow to get the position and size of each shape in the SvgEditor?
For example X, Y, Width and Height of a Rectangle.

**Comment by florian03-1** [comment]
Can you please describe in more detail where you want to get the data from?

Whenever you change or add a shape, you get information about the changed/new shape (including its position and size) via the ShapeChangedEventArgs (look at the ShapeChanged Property from SvgEditor)

**Comment by Wavey81** [comment]
It is exactly that i meant. I'm perhaps just too new to C# to know where to get the correct data :)
I'm looking in `OnShapeChanged(ShapeChangedEventArgs args)`, and checking what can be accessed in the args-variable. I just don't find anything about position and size.

**Comment by florian03-1** [comment]
You're almost there...
ShapeChangedEventArgs has a property called `Shape`This is the edited/added Shape property but it does not contains the position and size datas directly because the shape of the data depends on what type of shape it is (e.g. a circle has a center and a radius, a polygon has single points and a rectangle length height, as well as a starting point). 

The property in the EventArgs is from type Shape which is a base class. Each possible shape type is represented by a class which inherits from Shape. So you simply can cast the property to the corresponding shape type and you have an easy access to the properties like radius or width/height
